### ISSUE TITLE
Generate feedback.txt from grade.yml without uploading

### ISSUE THREAD

**Issue by madsobitsoe** [kfl/staffeli_nt#14]
This is as far as I can tell a part of #13 . 
(I might also have missed how to do it, if it is already possible)

In case the upload fails, it would be nice to still be able to generate the feedback.txt files and upload them either one at a time with upload-single.py or through the webinterface.

**Comment by kfl** [comment]
Yes, this is part of #13.

Currently, `grade.yml` is a strange mix of meta information about the hand-in and a grading sheet. The generation of `feedback.txt` from `grade.yml` is perhaps causing more trouble than it.

It would just be nice to have some structure on the feedback, so that the grade/points can automatically extracted and some basic sanity checks can be made. (Checking that all subtasks are graded, points are within limits and so on). Not sure what the right solution is.

**Comment by madsobitsoe** [comment]
The commit a74948ca46877e218b4666c738a5b0da2de35df1 does this, so I propose the issue is closed.
